# Use the official PostgreSQL image from Docker Hub
FROM postgres:latest

# Set environment variables
ENV POSTGRES_DB postgres_db
ENV POSTGRES_USER postgres_user
ENV POSTGRES_PASSWORD postgres_password

# Expose the default PostgreSQL port (5432)
EXPOSE 5432